### ISSUE TITLE
Revisar el texto de las sentencias it

### ISSUE THREAD

**Issue by evolentini** [gzocco/TP2-IOT#1]
El texto de las sentencias **_it_** describe en palabras lo que se espera, en este caso sería "En la lista hay un elemento almacenado". 

https://github.com/gzocco/TP2-IOT/blob/df25e98e9b46fc753d96adab12b327a24712a912/test/test_lista.js#L41

Si te sirve de referencia las sentencias _describe_ son equivalentes a las sentencias **_Given_** y **_When_** de BDD y las sentencias **_it_** son equivalentes a los **_Then_** y por esto mismo no deberían tener código adentro, solo verificaciones. 

https://github.com/gzocco/TP2-IOT/blob/df25e98e9b46fc753d96adab12b327a24712a912/test/test_lista.js#L113-L116

**Comment by gzocco** [comment]
Modifique textos y deje solo verificaciones.
