### ISSUE TITLE
El requisito se refiere al tipo de datos y no al contenido de la cadena

### ISSUE THREAD

**Issue by evolentini** [gzocco/TP2-IOT#2]
Lo que se platea no es este tipo de prueba
https://github.com/gzocco/TP2-IOT/blob/df25e98e9b46fc753d96adab12b327a24712a912/test/test_lista.js#L140-L143
sino este tipo
```javascript
it("Agrego un elemento con clave que NO cumple condicion", function () {
    lista.add( 23, "1234");      
    assert.equal(lista.count(), 3);  
}) 
```
Es decir que el primer argumento no es del tipo string sino otro tipo de datos.

**Comment by gzocco** [comment]
Verifique con otro tipo de dato distinto a string.
