### ISSUE TITLE
Faltaría probar eliminar un elemento que no está en la lista

### ISSUE THREAD

**Issue by evolentini** [gzocco/TP2-IOT#3]
https://github.com/gzocco/TP2-IOT/blob/df25e98e9b46fc753d96adab12b327a24712a912/test/test_lista.js#L177
https://github.com/gzocco/TP2-IOT/blob/df25e98e9b46fc753d96adab12b327a24712a912/test/test_lista.js#L187
https://github.com/gzocco/TP2-IOT/blob/df25e98e9b46fc753d96adab12b327a24712a912/test/test_lista.js#L199

**Comment by gzocco** [comment]
Agregué esa prueba.
