### ISSUE TITLE
Se debe refactorizar el código de producción

### ISSUE THREAD

**Issue by evolentini** [gzocco/TP2-IOT#4]
La lógica de estos tres lazos es la misma: buscar si la clave está en el arreglo y determinar el indice del par. 

https://github.com/gzocco/TP2-IOT/blob/df25e98e9b46fc753d96adab12b327a24712a912/src/lista.js#L17-L18
https://github.com/gzocco/TP2-IOT/blob/df25e98e9b46fc753d96adab12b327a24712a912/src/lista.js#L30-L31
https://github.com/gzocco/TP2-IOT/blob/df25e98e9b46fc753d96adab12b327a24712a912/src/lista.js#L61-L62

Esto se debería resolver en una función interna, la cual es usada por las funciones **_add_**, **_find_** y **_delete_**. De esta forma es mucho más fácil cambiar detalles de la implementación, por ejemplo usando no utilizar un arreglo para almacenar los pares.

**Comment by gzocco** [comment]
Se refactorizo.
