### ISSUE TITLE
El código de producción todavía necesita refactorizarse

### ISSUE THREAD

**Issue by evolentini** [gzocco/TP2-IOT#5]
Todavía hay mucho código que puede eliminarse, cómo por ejemplo todas las comparaciones ` if (this.#elementos.length >= 1) {`, las cuales no hacen falta porque la función `findIndex` se puede llamar con el vector vacío sin problemas.

https://github.com/gzocco/TP2-IOT/blob/22faf07252f991d843e7b1ee99e41e5d9710ed50/src/lista.js#L25

https://github.com/gzocco/TP2-IOT/blob/22faf07252f991d843e7b1ee99e41e5d9710ed50/src/lista.js#L41

https://github.com/gzocco/TP2-IOT/blob/22faf07252f991d843e7b1ee99e41e5d9710ed50/src/lista.js#L57

https://github.com/gzocco/TP2-IOT/blob/22faf07252f991d843e7b1ee99e41e5d9710ed50/src/lista.js#L69

También permanece el código de revisión del contenido de la clave que no es necesario

https://github.com/gzocco/TP2-IOT/blob/22faf07252f991d843e7b1ee99e41e5d9710ed50/src/lista.js#L39

**Comment by gzocco** [comment]
Se refactoriza codigo de produccion.
